language: python
python:
    - "3.6"
install: "pip install -r requirements.txt"
before_script:
  - python setup.py install
script:
    - flake8
    - coverage run manage.py test
after_success:
    - coveralls
