language: python
python:
    - "3.6"
install: "pip install -e .[dev]"
before_script:
  - python setup.py install
  - python setup.py loaddb
script:
    - flake8
    - coverage run manage.py test
after_success:
    - coveralls
