# Generated by Django 2.0 on 2018-09-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default=False, max_length=35)),
                ('email', models.EmailField(default=False, max_length=254, unique=True)),
                ('telephone', models.CharField(default=False, max_length=11)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=255, null=True)),
                ('addr', models.CharField(max_length=255)),
                ('additional_addr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('week_day', models.IntegerField(choices=[(1, 'Domingo'), (2, 'Segunda-feira'), (3, 'Terça-feira'), (4, 'Quarta-feira'), (5, 'Quinta-feira'), (6, 'Sexta-feira'), (7, 'Sábado')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizations.Organization')),
            ],
        ),
    ]
