# Generated by Django 2.0 on 2018-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default=False, max_length=35)),
                ('cnpj', models.CharField(default=False, max_length=15)),
                ('social_reason', models.CharField(default=False, max_length=25)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('telephone', models.CharField(default=False, max_length=11)),
            ],
        ),
    ]
