# Generated by Django 2.0 on 2018-07-28 13:27

from django.db import migrations, models
import organizations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cnpj',
            field=models.CharField(default=False, max_length=15, unique=True, validators=[organizations.validators.validate_CNPJ]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(default=False, max_length=254, unique=True),
        ),
    ]
